name: 'Dependency Review'

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Fail the workflow if high or critical vulnerabilities are found
          fail-on-severity: high
          # Allow specific licenses only
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, ISC, CC0-1.0, Unlicense
          # Warn about packages with these licenses
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0
          # Comment on PR with dependency changes
          comment-summary-in-pr: always